[package]
name = "buddy-slab-allocator"
version = "0.1.0"
edition = "2021"
authors = ["Song Zhiyong <songzhyo@qq.com>"]
description = "Memory allocator with Buddy and Slab allocation"
documentation = "https://docs.rs/buddy-slab-allocator"
repository = "https://github.com/arceos-hypervisor/buddy-slab-allocator"
readme = "README.md"
license = "Apache-2.0"
keywords = ["buddy", "slab", "allocator"]
categories = ["memory-management", "no-std", "embedded"]

[features]
default = []
log = ["dep:log"]
tracking = []
# Enable benchmarking (requires criterion and rand as regular dependencies)
bench = ["dep:criterion", "dep:rand"]

[dependencies]
log = { version = "0.4", optional = true }
cfg-if = "1.0"
criterion = { version = "0.4", features = ["html_reports"], optional = true }
rand = { version = "0.8", features = ["small_rng"], optional = true }

[[bench]]
name = "global_allocator"
harness = false
required-features = ["bench"]

[[bench]]
name = "buddy_allocator"
harness = false
required-features = ["bench"]

[[bench]]
name = "slab_allocator"
harness = false
required-features = ["bench"]

[[bench]]
name = "stability"
harness = false
required-features = ["bench"]



