[package]
name = "buddy-slab-allocator"
version = "0.2.0"
edition = "2021"
authors = ["Song Zhiyong <songzhyo@qq.com>"]
description = "Memory allocator with Buddy and Slab allocation"
documentation = "https://docs.rs/buddy-slab-allocator"
repository = "https://github.com/arceos-hypervisor/buddy-slab-allocator"
readme = "README.md"
license = "Apache-2.0"
keywords = ["buddy", "slab", "allocator"]
categories = ["memory-management", "no-std", "embedded"]

[features]
default = []
log = ["dep:log"]
tracking = []

[dependencies]
axallocator = "0.2"
cfg-if = "1.0"
log = { version = "0.4", optional = true }

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
rand = { version = "0.8", features = ["small_rng"] }

[[bench]]
name = "global_allocator"
harness = false

[[bench]]
name = "buddy_allocator"
harness = false

[[bench]]
name = "slab_allocator"
harness = false

[[bench]]
name = "stability"
harness = false
