[package]
authors = ["Song Zhiyong <songzhyo@qq.com>"]
categories = ["memory-management", "no-std", "embedded"]
description = "Memory allocator with Buddy and Slab allocation"
documentation = "https://docs.rs/buddy-slab-allocator"
edition = "2021"
keywords = ["buddy", "slab", "allocator"]
license = "Apache-2.0"
name = "buddy-slab-allocator"
readme = "README.md"
repository = "https://github.com/arceos-hypervisor/buddy-slab-allocator"
version = "0.2.0"

[features]
default = []

[dependencies]
log = "0.4"
spin = "0.10"

[dev-dependencies]
rand = {version = "0.10", features = ["std_rng"]}
